### ISSUE TITLE
Any chance you might update this fella?

### ISSUE THREAD

**Issue by MostHated** [psuong/arcade-vehicle-controller#1]
Hey there,
    I just came across this and was pretty excited with how helpful this looked. It has been a good bit of time since it was updated it looks like, I was wondering if perhaps you might be thinking of doing any sort of updates to it anytime soon to reflect some of the newer API changes and such? 

I have a small waypoint and pathfinding system I created for my game and have been trying to learn how to convert my vehicles and some of the people to use ECS and this seemed like a great asset/systems to learn from. I had noticed though that upon importing there were of course errors when trying to use it in newer versions of Unity / the ECS API's. 

I very much appreciate you having released it in the first place for the community, and hope that one day you might have some free time and might consider updating it!
Thanks,
-MH

Edit - Shoot, there are other things missing that I can't find an appropriate replacement for either, like IDictionaryWrapper<>, IArrayWrapper<>, and ITupleArrayWrapper<,>. Oh well I suppose, at least I tried, lol.

**Comment by psuong** [comment]
Hey there, there's a good chance I won't be updating this repo specifically anytime soon, since this was pulled out of my game. 

I'll most likely update it but there's currently no ETA on my roadmap. As of those interface Wrappers they simply allowed Scriptable Object to act like their common data structure counterpart (dictionaries, arrays, and tuple arrays).

**Comment by MostHated** [comment]
I appreciate the reply, as well as the honesty. I believe I may have it close to being usable. I saw your Common-Structures repo and used the Tuple files from in there but one of the last errors I seem to be getting from Unity, even with those files is, for example : 

    Assets\ArcadeRacer\Hybrid\Systems\CheckpointDetectionSystem.cs(50,43): error CS0117: 'Tuple<int, int>' does not contain a definition for 'CreateTuple'

I can't see to find anything that has the function of CreateTuple anywhere. Was that something that was left out on purpose?

The other one is:

    Assets\ArcadeRacer\Pure\Systems\VehicleSelectionScreenInputHandler.cs(22,68): error CS0103: The name 'device' does not exist in the current context

I saw you were using InControl, which I happen to have owned, so I threw it in there, not sure if 'device' was something created using that?

Once I can figure those out, I think it might be ok. I have been doing nothing but research on ECS/Jobs since I posted that question and luckily I have learned enough that I was able to get this mostly fixed up. There wasn't really too terribly much else luckily. : D

**Comment by psuong** [comment]
1. `Tuple<int, int>.CreateTuple(...)` is the same as constructing a `new Tuple<int, int>()`. The common-structures module was created before C# 6 was supported in Unity so those can be replaced with C#'s `ValueTuple<>`.
2. The `device` was actually a proprietary framework I can't release and is supposed to handle any type of controllers. The logic was to pool a series of controllers and assign each GUID associated to a Player ID. You can certainly replace logic there and attempt to use your own controller pooling system if you'd like.

**Comment by psuong** [comment]
Closing this until I'll readdress the repository.
